name: aldente
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pocketbase: ^0.18.1
  persistent_bottom_nav_bar: ^5.0.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  flutter_cool_card_swiper: ^0.0.4
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.0
  flutter_login: ^5.0.0
  chatview: ^1.3.1
  path_provider: ^2.1.3
  get_storage: ^2.1.1
  get: ^4.6.6
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  tflite_flutter: ^0.10.4
  flutter_gemma: ^0.2.1
  flutter_bloc: ^8.1.6
  flutter_markdown: ^0.7.2

dependency_overrides:
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  web:
    generate: true
    image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
  macos:
    generate: true
    image_path: "assets/icon.png"

get_cli: 
  sub_folder: false

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icons/
    - assets/images/
    - images/asset.png
    - images/asset1.png    
    - images/asset2.png
    - images/google.png
    - images/facebook.png
    - images/apple.png      
    - assets/models/yolov8n.tflite
